preload = /home/geeks/wallpapers/voyager-mellow.jpg

wallpaper = eDP-1, /home/geeks/wallpapers/voyager-mellow.jpg
wallpaper = eDP-2, /home/geeks/wallpapers/one.jpg
wallpaper = eDP-3, /home/geeks/wallpapers/Config.jpg
wallpaper = eDP-4, /home/geeks/wallpapers/anime_sky.jpg
